    
    </div><!-- #content-wrap -->
    
	<div id="footer">
		<p>This page was generated by <span id="generator-link"><a href="http://wordpress.org/" title="<?php _e('WordPress', 'sandbox'); ?>" rel="generator"><?php _e('WordPress', 'sandbox'); ?></a></span>
		and <span id="theme-link"><a href="http://themeshaper.com/" title="<?php _e('A ThemeShaper Theme', 'sandbox'); ?>" rel="designer"><?php _e('MNML', 'sandbox'); ?></a></span>.</p>
	</div><!-- #footer -->

</div><!-- #wrapper .hfeed -->

<?php wp_footer() ?>

</body>
</html>